<div id="page-footer">
            <div class="row align-justify">
                <nav id="footer-navigation" role="navigation">
                    <div class="columns medium-3">
                        <ul class="menu vertical compact component-red">
                            <li class="menu-label">Products</li>
                            <li class="menu-item"><a href="https://www2.microstrategy.com/producthelp/Current/Readme/en-us/content/whats_new.htm">What's New</a>
                            </li>
                            <li class="menu-item"><a href="https://www2.microstrategy.com/producthelp/Current/Hyper/index.htm">HyperIntelligence</a>
                            </li>
                            <li class="menu-item"><a href="https://www2.microstrategy.com/producthelp/Current/Workstation/WebHelp/Lang_1033/index.htm">Workstation</a>
                            </li>
                            <li class="menu-item"><a href="https://www2.microstrategy.com/producthelp/Current/Cloud/index.htm">Cloud Platform</a>
                            </li>
                        </ul>
                    </div>
                    <div class="columns medium-3">
                        <ul class="menu vertical compact component-blue">
                            <li class="menu-label">Interact</li>
                            <li class="menu-item"><a href="mailto:documentationfeedback@microstrategy.com">Documentation Feedback</a>
                            </li>
                            <li class="menu-item"><a href="https://community.microstrategy.com/s/ideas">Idea Exchange</a>
                            </li>
                            <li class="menu-item"><a href="https://community.microstrategy.com/s/discussions">Community Discussions</a>
                            </li>
                        </ul>
                    </div>
                    <div class="columns medium-3">
                        <ul class="menu vertical compact component-orange">
                            <li class="menu-label">Resources</li>
                            <li class="menu-item"><a href="https://community.microstrategy.com/s/learning-center">Learning Center</a>
                            </li>
                            <li class="menu-item"><a href="https://www2.microstrategy.com/producthelp/Current/Readme/en-us/content/certified_configurations.htm">Platform Certifications</a>
                            </li>
                            <li class="menu-item"><a href="https://www.microstrategy.com/us/resources/library">Resource Library</a>
                            </li>
                            <li class="menu-item"><a href="https://www.microstrategy.com/us/services/technical-support">Technical Support</a>
                            </li>
                        </ul>
                    </div>
                    <div class="columns medium-3">
                        <ul class="menu vertical compact component-navy-blue">
                            <li class="menu-label">Company</li>
                            <li class="menu-item"><a href="https://www.microstrategy.com/us/company/press">Press Center</a>
                            </li>
                            <li class="menu-item"><a href="https://www.microstrategy.com/us/company/careers">Careers</a>
                            </li>
                            <li class="menu-item"><a href="https://www.microstrategy.com/us/company/contact">Contact MicroStrategy</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div><div id="legal-row" class="row">
            <div id="copyright-column" class="columns small-12 medium-6">
                <p id="copyright">Copyright © 2019 MicroStrategy Incorporated. All Rights Reserved.</p>
            </div>
            <div id="legal-links" class="columns small-12 medium-5 medium-offset-1">
                <nav role="navigation">
                    <ul class="menu">
                        <li class="menu-item"><a href="https://www.microstrategy.com/us/legal/legal-policies">Legal Policies |</a>
                        </li>
                        <li class="menu-item"><a href="https://www.microstrategy.com/us/legal/legal-policies/privacy-policy">Privacy Policy |</a>
                        </li>
                        <li class="menu-item"><a href="https://www.microstrategy.com/us/legal/legal-policies/terms-of-use">Terms of Use |</a>
                        </li>
                        <li class="menu-item"><a href="https://www.microstrategy.com/us/legal/ethics-line" target="_blank">Ethics Line</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        </div>